/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'videoId' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'thumbnail' : ExternalBlob,
  'submittedAt' : IDL.Int,
  'platform' : IDL.Text,
  'viewCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Comment)], []),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getFeaturedVideo' : IDL.Func([], [IDL.Opt(Video)], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'incrementViewCount' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], []),
  'likeVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], []),
  'submitVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
      [Video],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'videoId' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'thumbnail' : ExternalBlob,
    'submittedAt' : IDL.Int,
    'platform' : IDL.Text,
    'viewCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Comment)], []),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getFeaturedVideo' : IDL.Func([], [IDL.Opt(Video)], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'incrementViewCount' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], []),
    'likeVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], []),
    'submitVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
        [Video],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };