/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'videoId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'status' : VideoStatus,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'thumbnail' : ExternalBlob,
  'submittedAt' : Time,
  'platform' : IDL.Variant({
    'other' : IDL.Null,
    'instagram' : IDL.Null,
    'youtube' : IDL.Null,
  }),
  'viewCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Comment)], []),
  'approveVideo' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getFeaturedVideo' : IDL.Func([], [IDL.Opt(Video)], ['query']),
  'getPendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'incrementViewCount' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], []),
  'rejectVideo' : IDL.Func([IDL.Nat], [], []),
  'submitVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'other' : IDL.Null,
          'instagram' : IDL.Null,
          'youtube' : IDL.Null,
        }),
        ExternalBlob,
        IDL.Nat,
      ],
      [Video],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'videoId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'status' : VideoStatus,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'thumbnail' : ExternalBlob,
    'submittedAt' : Time,
    'platform' : IDL.Variant({
      'other' : IDL.Null,
      'instagram' : IDL.Null,
      'youtube' : IDL.Null,
    }),
    'viewCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Comment)], []),
    'approveVideo' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getFeaturedVideo' : IDL.Func([], [IDL.Opt(Video)], ['query']),
    'getPendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'incrementViewCount' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], []),
    'rejectVideo' : IDL.Func([IDL.Nat], [], []),
    'submitVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'other' : IDL.Null,
            'instagram' : IDL.Null,
            'youtube' : IDL.Null,
          }),
          ExternalBlob,
          IDL.Nat,
        ],
        [Video],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };